#!/usr/bin/env python
"""Compile .po files to .mo files for translations.

This script converts human-readable .po translation files to binary .mo files
that are used by Python's gettext module at runtime.

Usage:
    python compile_translations.py            # compile .po -> .mo
    python compile_translations.py --extract  # regenerate the .pot template

The script compiles every .po catalog found under compatibility/locales/
(one per language), writing each .mo file next to its source, e.g.:
    locales/de/LC_MESSAGES/compatibility.po -> locales/de/LC_MESSAGES/compatibility.mo

With --extract it instead regenerates compatibility/locales/compatibility.pot,
the template for new languages, from the `_('...')` calls in the package
source. Run it whenever a translatable message is added or changed; a test
fails while the template is out of date.

Copyright (c) 2021-2026 Rüdiger Voigt and contributors
Released under the Apache License 2.0
"""

import ast
import glob
import os
import struct
import sys


_PO_ESCAPES = {'n': '\n', 't': '\t', 'r': '\r', '"': '"', '\\': '\\'}

# Translation template, regenerated from the source by --extract.
SOURCE_DIR = 'compatibility'
POT_FILE = 'compatibility/locales/compatibility.pot'

# Fixed header: no creation date or version, so regenerating an unchanged
# source yields a byte-identical file. There is no Plural-Forms line: the
# library uses no plural messages, and the GNU placeholder
# (nplurals=INTEGER) breaks parsers such as Babel and Python's gettext.
_POT_HEADER = '''\
# Translation template for the compatibility package.
# Copyright (c) 2021-2026 Rüdiger Voigt and contributors
# This file is distributed under the same license as the compatibility package.
# Generated by `python compile_translations.py --extract`. Do not edit by hand.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: compatibility\\n"
"Report-Msgid-Bugs-To: \\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\\n"
"Language-Team: LANGUAGE <LL@li.org>\\n"
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
'''


def _escape_po(text):
    """Encode a string for use between the quotes of a .po line.

    The inverse of _unescape_po for the standard escape set.

    Args:
        text: The plain string.

    Returns:
        The escaped string.
    """
    return (text.replace('\\', '\\\\').replace('"', '\\"')
            .replace('\n', '\\n').replace('\t', '\\t').replace('\r', '\\r'))


def extract_messages(source_dir=SOURCE_DIR):
    """Collect the translatable strings from the package source.

    A translatable string is the literal first argument of a call to `_`
    (e.g. `self._('Missing package name!')`), in any .py file below
    source_dir.

    Args:
        source_dir: Directory to scan recursively.

    Returns:
        Dict mapping each msgid to its source locations ('file:line'),
        ordered by first occurrence (by file, then line).

    Raises:
        ValueError: If `_` is called with anything but a single string
            literal, since such a message cannot be extracted.
    """
    found = []
    for path in sorted(glob.glob(os.path.join(source_dir, '**', '*.py'),
                                 recursive=True)):
        location = path.replace(os.sep, '/')
        with open(path, encoding='utf-8') as f:
            tree = ast.parse(f.read(), filename=path)
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call):
                continue
            func = node.func
            name = (func.attr if isinstance(func, ast.Attribute)
                    else func.id if isinstance(func, ast.Name) else None)
            if name != '_':
                continue
            if (len(node.args) != 1 or node.keywords
                    or not isinstance(node.args[0], ast.Constant)
                    or not isinstance(node.args[0].value, str)):
                raise ValueError(
                    f'{location}:{node.lineno}: _() must be called with a '
                    'single string literal to be extractable.')
            found.append((location, node.lineno, node.col_offset,
                          node.args[0].value))
    messages = {}
    for location, line, _col, msgid in sorted(found):
        messages.setdefault(msgid, []).append(f'{location}:{line}')
    return messages


def build_pot(messages):
    """Render extracted messages as the contents of a .pot template.

    Args:
        messages: Dict as returned by extract_messages().

    Returns:
        The template text.
    """
    entries = [_POT_HEADER]
    for msgid, locations in messages.items():
        lines = ['#: ' + ' '.join(locations)]
        if '%' in msgid:
            lines.append('#, python-format')
        lines.append(f'msgid "{_escape_po(msgid)}"')
        lines.append('msgstr ""')
        entries.append('\n'.join(lines) + '\n')
    return '\n'.join(entries)


def write_pot(pot_file=POT_FILE, source_dir=SOURCE_DIR):
    """Regenerate the .pot template from the source.

    Args:
        pot_file: Path of the template to write.
        source_dir: Directory to extract messages from.

    Returns:
        The number of messages written.
    """
    messages = extract_messages(source_dir)
    with open(pot_file, 'w', encoding='utf-8', newline='\n') as f:
        f.write(build_pot(messages))
    return len(messages)


def _unescape_po(text):
    """Decode the backslash escape sequences used inside .po quoted strings.

    Handles the standard set (\\n, \\t, \\r, \\", \\\\). An unknown escape is
    left untouched (backslash preserved). This is needed so the header entry,
    which encodes its fields with \\n, becomes real newlines that gettext can
    parse.

    Args:
        text: A raw string taken from between the quotes of a .po line.

    Returns:
        The unescaped string.
    """
    result = []
    i = 0
    while i < len(text):
        if text[i] == '\\' and i + 1 < len(text):
            nxt = text[i + 1]
            result.append(_PO_ESCAPES.get(nxt, '\\' + nxt))
            i += 2
        else:
            result.append(text[i])
            i += 1
    return ''.join(result)


def _parse_po(po_file):
    """Parse a .po file into a {msgid: msgstr} mapping.

    The empty-msgid header entry is preserved so its metadata (Content-Type,
    Language, Plural-Forms, ...) is carried into the compiled catalog.

    Args:
        po_file: Path to the source .po file.

    Returns:
        Dict mapping each msgid to its msgstr (including the '' header entry).
    """
    with open(po_file, encoding='utf-8') as f:
        lines = f.read().split('\n')

    messages = {}
    current_msgid = []
    current_msgstr = []
    state = None  # tracks whether we're reading a msgid or a msgstr

    def flush():
        # Save the entry just parsed (including the '' header entry).
        if current_msgid and current_msgstr:
            messages[''.join(current_msgid)] = ''.join(current_msgstr)

    for line in lines:
        line = line.strip()
        if line.startswith('msgid '):
            flush()
            current_msgid[:] = [_unescape_po(line[7:-1])]   # strip 'msgid "' / '"'
            current_msgstr[:] = []
            state = 'msgid'
        elif line.startswith('msgstr '):
            current_msgstr[:] = [_unescape_po(line[8:-1])]  # strip 'msgstr "' / '"'
            state = 'msgstr'
        elif line.startswith('"') and line.endswith('"'):
            text = _unescape_po(line[1:-1])                 # continuation line
            if state == 'msgid':
                current_msgid.append(text)
            elif state == 'msgstr':
                current_msgstr.append(text)
    flush()
    return messages


def _serialize_mo(catalog):
    """Serialize a message catalog into GNU gettext .mo binary format.

    Args:
        catalog: Dict mapping msgid to msgstr (including the '' metadata header).

    Returns:
        The .mo file contents as bytes.
    """
    keys = sorted(catalog.keys())

    offsets = []
    ids = b''
    strs = b''
    for key in keys:
        key_bytes = key.encode('utf-8')
        val_bytes = catalog[key].encode('utf-8')
        offsets.append((len(ids), len(key_bytes), len(strs), len(val_bytes)))
        ids += key_bytes + b'\x00'
        strs += val_bytes + b'\x00'

    keystart = 7 * 4 + 16 * len(keys)
    valuestart = keystart + len(ids)
    koffsets = [(l1, keystart + o1) for o1, l1, _, _ in offsets]
    voffsets = [(l2, valuestart + o2) for _, _, o2, l2 in offsets]

    output = bytearray()
    output += struct.pack('<I', 0x950412de)             # magic number (LE)
    output += struct.pack('<I', 0)                       # version
    output += struct.pack('<I', len(keys))              # number of entries
    output += struct.pack('<I', 7 * 4)                  # offset of originals table
    output += struct.pack('<I', 7 * 4 + len(keys) * 8)  # offset of translations table
    output += struct.pack('<I', 0)                       # hash table size (unused)
    output += struct.pack('<I', 0)                       # hash table offset (unused)
    for length, offset in koffsets:
        output += struct.pack('<II', length, offset)
    for length, offset in voffsets:
        output += struct.pack('<II', length, offset)
    output += ids
    output += strs
    return bytes(output)


def compile_po_to_mo(po_file, mo_file):
    """Compile .po to .mo using Python stdlib only (no external dependencies).

    Args:
        po_file: Path to source .po file
        mo_file: Path to output .mo file
    """
    # The parsed catalog already includes the '' header entry from the .po
    # (Content-Type, Language, Plural-Forms, ...), so no metadata is injected
    # here -- the .po file is the single source of truth.
    catalog = _parse_po(po_file)
    # Leave out untranslated entries (empty msgstr), like GNU msgfmt does.
    # Otherwise gettext would return '' for them instead of falling back to
    # the English msgid.
    catalog = {msgid: msgstr for msgid, msgstr in catalog.items() if msgstr}
    with open(mo_file, 'wb') as f:
        f.write(_serialize_mo(catalog))


if __name__ == '__main__':
    if sys.argv[1:] == ['--extract']:
        # Regenerate the translation template from the source.
        count = write_pot()
        print(f'Done! Wrote {count} messages to {POT_FILE}')
        sys.exit(0)
    if sys.argv[1:]:
        sys.exit('Usage: python compile_translations.py [--extract]')
    # Compile every .po catalog under the locales tree (one per language).
    po_files = sorted(
        glob.glob('compatibility/locales/**/*.po', recursive=True))
    if not po_files:
        print('No .po files found under compatibility/locales/.')
    for po_file in po_files:
        mo_file = os.path.splitext(po_file)[0] + '.mo'
        print(f"Compiling {po_file} to {mo_file}...")
        compile_po_to_mo(po_file, mo_file)
        print(f"Done! Created {mo_file} ({os.path.getsize(mo_file)} bytes)")
