# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pre-Release-Python

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: APT Update
      run: sudo apt update

    - uses: actions/checkout@v2

    - name: Set up beta version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.0-beta.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pytest tests.py
